package com.tranzo.tranzo_user_ms.notification.enums;

public enum NotificationType {
    DRAFT_TRIP_REMINDER,
    UPCOMING_TRIP,
    TRIP_COMPLETED,
    TRIP_CANCELLED,
    JOIN_REQUEST_RECEIVED,
    JOIN_REQUEST_APPROVED,
    JOIN_REQUEST_REJECTED,
    MEMBER_JOINED_TRIP,
    MEMBER_LEFT_OR_REMOVED_TRIP,
    MEMBER_PROMOTED_TO_CO_HOST,
    TRIP_FULL_CAPACITY_REACHED,
    TRIP_MARKED_FULL_BY_HOST,
    TRIP_DETAILS_CHANGED,
    TRIP_QUESTION_ASKED,
    TRIP_QUESTION_ANSWERED
}
