package com.tranzo.tranzo_user_ms.trip.enums;

/**
 * Error codes for trip module operations
 */
public enum TripErrorCode {
    // Trip existence and access errors
    TRIP_NOT_FOUND("TRIP_NOT_FOUND"),
    TRIP_ACCESS_DENIED("TRIP_ACCESS_DENIED"),

    // Trip status errors
    INVALID_TRIP_STATUS_TRANSITION("INVALID_TRIP_STATUS_TRANSITION"),
    TRIP_ALREADY_CANCELLED("TRIP_ALREADY_CANCELLED"),
    TRIP_NOT_PUBLISHED("TRIP_NOT_PUBLISHED"),
    TRIP_ALREADY_PUBLISHED("TRIP_ALREADY_PUBLISHED"),

    // Trip validation errors
    TITLE_MISSING("TITLE_MISSING"),
    DESCRIPTION_MISSING("DESCRIPTION_MISSING"),
    DESTINATION_MISSING("DESTINATION_MISSING"),
    START_DATE_MISSING("START_DATE_MISSING"),
    END_DATE_MISSING("END_DATE_MISSING"),
    INVALID_DATE_RANGE("INVALID_DATE_RANGE"),
    ESTIMATED_BUDGET_MISSING("ESTIMATED_BUDGET_MISSING"),
    INVALID_ESTIMATED_BUDGET("INVALID_ESTIMATED_BUDGET"),
    MAX_PARTICIPANTS_MISSING("MAX_PARTICIPANTS_MISSING"),
    INVALID_MAX_PARTICIPANTS("INVALID_MAX_PARTICIPANTS"),
    JOIN_POLICY_MISSING("JOIN_POLICY_MISSING"),
    ITINERARY_MISSING("ITINERARY_MISSING"),

    // Trip capacity and membership errors
    TRIP_FULL("TRIP_FULL"),
    TRIP_ALREADY_MARKED_FULL("TRIP_ALREADY_MARKED_FULL"),
    USER_NOT_TRIP_MEMBER("USER_NOT_TRIP_MEMBER"),
    USER_ALREADY_TRIP_MEMBER("USER_ALREADY_TRIP_MEMBER"),
    HOST_CANNOT_LEAVE_TRIP("HOST_CANNOT_LEAVE_TRIP"),
    PARTICIPANT_NOT_FOUND("PARTICIPANT_NOT_FOUND"),

    // Trip member role errors
    INVALID_ROLE_CHANGE("INVALID_ROLE_CHANGE"),
    USER_ALREADY_CO_HOST("USER_ALREADY_CO_HOST"),
    ONLY_MEMBER_CAN_BE_PROMOTED("ONLY_MEMBER_CAN_BE_PROMOTED"),
    HOST_CANNOT_BE_CO_HOST("HOST_CANNOT_BE_CO_HOST"),

    // Trip join request errors
    JOIN_REQUEST_NOT_FOUND("JOIN_REQUEST_NOT_FOUND"),
    JOIN_REQUEST_NOT_PENDING("JOIN_REQUEST_NOT_PENDING"),
    JOIN_REQUEST_ALREADY_EXISTS("JOIN_REQUEST_ALREADY_EXISTS"),
    HOST_CANNOT_CREATE_JOIN_REQUEST("HOST_CANNOT_CREATE_JOIN_REQUEST"),
    TRIP_NOT_JOINABLE("TRIP_NOT_JOINABLE"),
    INVALID_JOIN_REQUEST_CANCEL("INVALID_JOIN_REQUEST_CANCEL"),

    // Trip Q&A errors
    QUESTION_EMPTY("QUESTION_EMPTY"),
    QNA_ALREADY_ANSWERED("QNA_ALREADY_ANSWERED"),
    QNA_NOT_FOUND("QNA_NOT_FOUND"),
    INVALID_QNA_STATUS("INVALID_QNA_STATUS"),

    // Trip reporting errors
    TRIP_ALREADY_REPORTED("TRIP_ALREADY_REPORTED"),
    REPORT_REASON_EMPTY("REPORT_REASON_EMPTY"),
    REPORT_NOT_FOUND("REPORT_NOT_FOUND"),

    // Trip broadcast errors
    TRIP_NOT_BROADCASTABLE("TRIP_NOT_BROADCASTABLE");

    private final String code;

    TripErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
