package com.tranzo.tranzo_user_ms.trip.enums;

public enum TripPublishErrorCode {

    TRIP_NOT_FOUND,
    TRIP_ALREADY_PUBLISHED,
    TRIP_NOT_PUBLISHED,

    TITLE_MISSING,
    DESCRIPTION_MISSING,
    DESTINATION_MISSING,

    START_DATE_MISSING,
    END_DATE_MISSING,
    INVALID_DATE_RANGE,

    ESTIMATED_BUDGET_MISSING,
    INVALID_ESTIMATED_BUDGET,

    MAX_PARTICIPANTS_MISSING,
    INVALID_MAX_PARTICIPANTS,

    JOIN_POLICY_MISSING,
    VISIBILITY_STATUS_MISSING,

    TRIP_POLICY_MISSING,
    ITINERARY_MISSING
}

